version: '3'
services:
  rabbitmq-daemon:
    image: 'rabbitmq:3-management'
    hostname: 'rabbitmq'
    ports: 
      - "8080:15672"
    environment: 
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=demo
  rabbitmq-tester:
    build: rabbitmq-tester/.
    ports:
      - "8081:80"
    depends_on:
      - "rabbitmq-daemon"